<#
.SYNOPSIS
    Creates Blue Iris 6 camera entries from a token CSV file.

.DESCRIPTION
    Reads camera tokens from a CSV (generated by Generate-Tokens.ps1),
    stops the Blue Iris service, creates registry entries for each camera,
    and restarts the service.

.PARAMETER CsvPath
    Path to the CSV file with camera tokens.

.PARAMETER MainQuality
    Which quality to use for the main stream. Default: "low".
    Use "high" for better recording quality (more CPU/bandwidth).

.PARAMETER SubQuality
    Which quality to use for the sub stream. Default: "low".
    Sub stream is used for the grid view in Blue Iris.

.PARAMETER DryRun
    If specified, shows what would be done without making changes.

.EXAMPLE
    .\Setup-BlueIris.ps1 -CsvPath ".\camera_tokens_2026-02-18.csv"

.EXAMPLE
    .\Setup-BlueIris.ps1 -CsvPath ".\tokens.csv" -MainQuality "high" -SubQuality "low"

.EXAMPLE
    .\Setup-BlueIris.ps1 -CsvPath ".\tokens.csv" -DryRun

.NOTES
    IMPORTANT: Run as Administrator (registry writes require elevation).
    Part of the "Protect Your Iris" guide.
#>

param(
    [Parameter(Mandatory = $true)]
    [string]$CsvPath,

    [ValidateSet("high", "low")]
    [string]$MainQuality = "low",

    [ValidateSet("high", "low")]
    [string]$SubQuality = "low",

    [switch]$DryRun
)

# Verify CSV exists
if (!(Test-Path $CsvPath)) {
    Write-Host "ERROR: CSV file not found: $CsvPath" -ForegroundColor Red
    exit 1
}

$cameras = Import-Csv $CsvPath
Write-Host "`n=== Blue Iris Camera Setup ===" -ForegroundColor Cyan
Write-Host "CSV: $CsvPath ($($cameras.Count) cameras)" -ForegroundColor White
Write-Host "Main: $MainQuality | Sub: $SubQuality" -ForegroundColor White

if ($DryRun) {
    Write-Host "MODE: DRY RUN (no changes will be made)" -ForegroundColor Yellow
}

# Verify admin rights
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (!$isAdmin -and !$DryRun) {
    Write-Host "ERROR: This script must be run as Administrator." -ForegroundColor Red
    exit 1
}

# Backup existing registry
if (!$DryRun) {
    $backupPath = ".\bi6_backup_$(Get-Date -Format 'yyyyMMdd_HHmm').reg"
    Write-Host "`nBacking up registry to $backupPath..." -ForegroundColor Yellow
    reg export "HKLM\SOFTWARE\Perspective Software\Blue Iris" $backupPath /y 2>$null
    if ($LASTEXITCODE -eq 0) {
        Write-Host "  Backup saved." -ForegroundColor Green
    }
    else {
        Write-Host "  No existing Blue Iris registry to backup (fresh install?)." -ForegroundColor Yellow
    }

    # Stop Blue Iris
    Write-Host "Stopping Blue Iris service..." -ForegroundColor Yellow
    Stop-Service -Name "BlueIris" -Force -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 5
    Write-Host "  Service stopped." -ForegroundColor Green
}

# Create cameras
$regBase = "HKLM:\SOFTWARE\Perspective Software\Blue Iris\Cameras"
$created = 0
$skipped = 0

foreach ($cam in $cameras) {
    $name = $cam.Name
    $nvrIP = $cam.NvrIP

    # Determine tokens
    $mainTokenField = "${MainQuality}Token"
    $subTokenField = "${SubQuality}Token"
    $mainToken = $cam.$mainTokenField
    $subToken = $cam.$subTokenField

    if (!$mainToken -or $mainToken -eq "FAILED") {
        Write-Host "  SKIP: $name (no $MainQuality token)" -ForegroundColor Yellow
        $skipped++
        continue
    }
    if (!$subToken -or $subToken -eq "FAILED") {
        $subToken = $mainToken  # Fallback: use main token for sub
    }

    $regPath = "$regBase\$name"

    if ($DryRun) {
        Write-Host "  WOULD CREATE: $name (main=$($mainToken.Substring(0,8))..., sub=$($subToken.Substring(0,8))...)" -ForegroundColor Cyan
        $created++
        continue
    }

    # Create registry key
    if (!(Test-Path $regPath)) {
        New-Item -Path $regPath -Force | Out-Null
    }

    # All required properties
    $props = @{
        type          = 4
        ip            = $nvrIP
        ip_port       = 80
        ip_port2      = 7447
        ip_path       = "/$mainToken"
        ip_subpath    = "/$subToken"
        ip_path2      = "/$subToken"
        dsname        = "admin@${nvrIP}:80/${mainToken}/:7447:1[/${subToken}]"
        ipid          = "admin"
        ippw          = "YWRtaW4="
        ippwencode    = 1
        enable        = 1
        enabled       = 1
        active        = 254
        smartdecode   = 1
        bvr           = 1
        hwaccel       = 1
        gpu           = "any"
        ip_fps        = 10
        ip_device     = 135
        ip_camno      = 1
        ip_keepalives = 1
        ip_rtsptime   = 1
        screencap     = 1
        hidden        = 0
        format        = 0
        pixfmt        = 12
        rtp           = 0
        https         = 0
    }

    foreach ($key in $props.Keys) {
        $value = $props[$key]
        $type = if ($value -is [int]) { "DWord" } else { "String" }
        Set-ItemProperty -Path $regPath -Name $key -Value $value -Type $type
    }

    Write-Host "  OK: $name" -ForegroundColor Green
    $created++
}

Write-Host "`n=== Summary ===" -ForegroundColor Cyan
Write-Host "Created: $created | Skipped: $skipped" -ForegroundColor White

if (!$DryRun -and $created -gt 0) {
    # Set global optimizations
    $globalPath = "HKLM:\SOFTWARE\Perspective Software\Blue Iris"
    if (Test-Path $globalPath) {
        @{
            gpudecode       = 1
            hwaccel         = 1
            direct_to_disc  = 1
            limit_decode    = 1
            limit_live      = 1
            limit_streaming = 1
        }.GetEnumerator() | ForEach-Object {
            Set-ItemProperty -Path $globalPath -Name $_.Key -Value $_.Value -Type DWord
        }
        Write-Host "Global optimizations applied." -ForegroundColor Green
    }

    # Start Blue Iris
    Write-Host "`nStarting Blue Iris service..." -ForegroundColor Yellow
    Start-Service -Name "BlueIris"

    $waitTime = [math]::Max(120, $created * 3)
    Write-Host "Waiting $waitTime seconds for cameras to connect..." -ForegroundColor Cyan
    Start-Sleep -Seconds $waitTime

    Write-Host "`nDone! Open Blue Iris to verify camera status." -ForegroundColor Green
    Write-Host "Backup saved to: $backupPath" -ForegroundColor White
}
elseif ($DryRun) {
    Write-Host "`nDry run complete. No changes were made." -ForegroundColor Yellow
    Write-Host "Remove -DryRun flag to apply changes." -ForegroundColor White
}
